#!/usr/bin/env python3
"""Ground truth for the overwritten fixture: what happened to every deleted file.

The overwritten fixture used to record a rule - "deleted files whose clusters
fall in the overwritten region must classify RED; the remainder GREEN" - and
nothing about which files those were. Measured on the image it produced: 69
deleted files intact, 10 overwritten completely, and none overwritten in part,
so the YELLOW band of SPEC.md 5.7 was never exercised. A rule is an
expectation; a classifier cannot be graded against it.

This records outcomes instead, in three steps run by build_fixtures.sh:

  map     before anything is overwritten, locate every cluster of every
          deleted file by content, in file order
  damage  after the filesystem-level overwrites, write deliberate partial
          overwrites straight into chosen files' clusters, so that every band
          and every kind of evidence has a case
  truth   re-read every recorded cluster and say, per file, which were lost
          and how: overwritten and freed again, or now allocated to a live file

Usage:
  overmap.py map IMAGE CORPUS_DIR MANIFEST DELETED_JSON CLUSTER   > before.json
  overmap.py livefile PATH BYTES SEED CLUSTER                      > live.json
  overmap.py damage IMAGE BEFORE_JSON SEED MANIFEST                > damage.json
  overmap.py truth IMAGE BEFORE_JSON DAMAGE_JSON LIVE_JSON         > truth.json

The classification policy applied in `truth` was decided for Milestone 5 and is
stated once, in classify() below.
"""

import hashlib
import json
import mmap
import os
import random
import sys


def h(b):
    return hashlib.blake2b(b, digest_size=16).hexdigest()


# --------------------------------------------------------------------- map


def cmd_map(image, corpus_dir, manifest_path, deleted_json, cluster):
    manifest = json.load(open(manifest_path, encoding="utf-8"))
    deleted = json.load(open(deleted_json, encoding="utf-8"))
    files = {}
    for rel in deleted:
        with open(os.path.join(corpus_dir, rel.replace("/", os.sep)), "rb") as fh:
            data = fh.read()
        if hashlib.sha256(data).hexdigest() != manifest[rel]["sha256"]:
            raise SystemExit("%s: regenerated bytes do not match the manifest" % rel)
        files[rel] = data

    with open(image, "rb") as fh:
        mm = mmap.mmap(fh.fileno(), 0, access=mmap.ACCESS_READ)
        # NTFS on a whole-device image: clusters start at offset 0. Checked
        # rather than assumed - the first full cluster of any file must land on
        # the grid.
        phase = None
        for data in files.values():
            if len(data) >= cluster:
                at = mm.find(data[:cluster])
                if at >= 0:
                    phase = at % cluster
                    break
        if phase is None:
            raise SystemExit("no deleted file has a full cluster on disk to find the phase by")

        index = {}
        off = phase
        while off + cluster <= len(mm):
            index.setdefault(h(mm[off:off + cluster]), []).append(off)
            off += cluster

        out = {}
        for rel, data in sorted(files.items()):
            offsets, ambiguous = [], []
            prev = None
            for k in range(0, len(data), cluster):
                piece = data[k:k + cluster]
                if len(piece) == cluster:
                    cands = index.get(h(piece), [])
                else:
                    cands = []
                    start = prev + cluster if prev is not None else phase
                    hit = mm.find(piece, start)
                    while hit >= 0 and (hit - phase) % cluster:
                        hit = mm.find(piece, hit + 1)
                    if hit < 0:
                        hit = mm.find(piece, phase)
                        while hit >= 0 and (hit - phase) % cluster:
                            hit = mm.find(piece, hit + 1)
                    if hit >= 0:
                        cands = [hit]
                if not cands:
                    offsets = None
                    break
                if len(cands) > 1:
                    # Identical clusters elsewhere - an empty SQLite page, a
                    # run of zeros. Resolved below against the file's own
                    # clusters: a block repeated within one file is not
                    # ambiguous, only a copy outside it is.
                    ambiguous.append((k // cluster, cands))
                if prev is not None and prev + cluster in cands:
                    at = prev + cluster
                elif prev is not None and any(c > prev for c in cands):
                    at = min(c for c in cands if c > prev)
                else:
                    at = cands[0]
                offsets.append(at)
                prev = at
            if offsets is not None:
                own = set(offsets)
                # Ambiguous only if the same bytes also sit somewhere this file
                # does not: then which copy is this file's is not knowable from
                # content, and damaging it could hit another file. The corpus's
                # low-entropy blobs are one 4 KiB block repeated four times, and
                # counting that as ambiguous left no binary file to damage.
                ambiguous = [i for i, cands in ambiguous if any(c not in own for c in cands)]
            else:
                ambiguous = []
            entry = {"size": len(data), "ambiguous": ambiguous}
            if offsets is None:
                # Not on the cluster grid. A small NTFS file lives inside its
                # MFT record; the MFT is allocated, so nothing freed can reach
                # it. Confirm the bytes are in the image at all.
                if mm.find(data) < 0:
                    raise SystemExit("%s: deleted file not found in the image at all" % rel)
                entry["resident"] = True
                entry["clusters"] = []
            else:
                entry["resident"] = False
                entry["clusters"] = offsets
                entry["hashes"] = [h(data[k:k + cluster]) for k in range(0, len(data), cluster)]
            out[rel] = entry
        mm.close()
    json.dump({"cluster": cluster, "phase": phase, "files": out}, sys.stdout, indent=1, sort_keys=True)


# ---------------------------------------------------------------- livefile


def cmd_livefile(path, nbytes, seed, cluster):
    """Write a file that stays allocated, and record its clusters' hashes.

    Random bytes, not a pattern: a deleted file's cluster that now holds one of
    these was reallocated to a live file, and nothing about its content says
    so - only the filesystem's allocation does.
    """
    rng = random.Random(seed)
    data = bytes(rng.getrandbits(8) for _ in range(nbytes))
    with open(path, "wb") as fh:
        fh.write(data)
        fh.flush()
        os.fsync(fh.fileno())
    hashes = sorted({h(data[k:k + cluster]) for k in range(0, nbytes - cluster + 1, cluster)})
    json.dump({"bytes": nbytes, "seed": seed, "sha256": hashlib.sha256(data).hexdigest(),
               "cluster_hashes": hashes}, sys.stdout)


# ------------------------------------------------------------------ damage

# Each case exists to exercise one kind of evidence, and says which. `kinds` is
# tried in order and the first intact deleted file with enough clusters is
# chosen, by sorted path, so the choice is reproducible.
PLAN = [
    # A validator should localise one bad cluster in the middle of a file.
    {"case": "one-cluster-random-png", "kinds": ["png"], "min_clusters": 4,
     "which": "one-middle", "fill": "random", "evidence": "validator"},
    {"case": "one-cluster-random-mp4", "kinds": ["mp4"], "min_clusters": 4,
     "which": "one-middle", "fill": "random", "evidence": "validator"},
    {"case": "one-cluster-random-sqlite", "kinds": ["sqlite"], "min_clusters": 4,
     "which": "one-middle", "fill": "random", "evidence": "validator"},
    # The header gone: the file cannot even be identified.
    {"case": "header-random-jpeg", "kinds": ["jpeg"], "min_clusters": 4,
     "which": "header", "fill": "random", "evidence": "validator"},
    {"case": "header-random-png", "kinds": ["png"], "min_clusters": 4,
     "which": "header", "fill": "random", "evidence": "validator"},
    # Half or more gone. A validator that stops at its first break can confirm
    # only one of these clusters.
    {"case": "half-random-mp4", "kinds": ["mp4"], "min_clusters": 6,
     "which": "half", "fill": "random", "evidence": "validator"},
    {"case": "half-uniform-binary", "kinds": ["binary"], "min_clusters": 4,
     "which": "half", "fill": "uniform", "evidence": "uniform"},
    # No validator: text must look like text, and no file is one repeated byte.
    {"case": "one-cluster-random-text", "kinds": ["text"], "min_clusters": 3,
     "which": "one-middle", "fill": "random", "evidence": "text"},
    {"case": "one-cluster-uniform-text", "kinds": ["text"], "min_clusters": 3,
     "which": "one-middle", "fill": "uniform", "evidence": "uniform"},
    {"case": "one-cluster-uniform-binary", "kinds": ["binary"], "min_clusters": 4,
     "which": "one-middle", "fill": "uniform", "evidence": "uniform"},
    # Deliberately undetectable: random bytes over random bytes, in a format
    # with no structure. Present so the report shows what "GREEN on evidence"
    # cannot see, rather than a fixture that only contains what it can.
    {"case": "one-cluster-random-binary-no-evidence", "kinds": ["binary"], "min_clusters": 4,
     "which": "one-middle", "fill": "random", "evidence": "none"},
]


def piece_len(e, i, C):
    n = len(e["clusters"])
    return C if i < n - 1 else e["size"] - C * (n - 1)


def overmap_h(mm, e, i, C):
    o = e["clusters"][i]
    return h(mm[o:o + piece_len(e, i, C)])


def intact(mm, e, C):
    return all(h(mm[o:o + piece_len(e, i, C)]) == want
               for i, (o, want) in enumerate(zip(e["clusters"], e["hashes"])))


def targets(step, n):
    if step["which"] == "header":
        return [0]
    if step["which"] == "one-middle":
        return [n // 2]
    # half, never the header, so the header rule is not what fires
    return list(range(1, 1 + (n + 1) // 2))


def cmd_damage(image, before_json, seed, manifest_path):
    before = json.load(open(before_json, encoding="utf-8"))
    manifest = json.load(open(manifest_path, encoding="utf-8"))
    C = before["cluster"]
    rng = random.Random(seed)
    done, used = [], set()
    with open(image, "r+b") as fh:
        mm = mmap.mmap(fh.fileno(), 0)
        for step in PLAN:
            chosen = None
            skipped = []
            for rel in sorted(before["files"]):
                e = before["files"][rel]
                if manifest[rel]["kind"] not in step["kinds"]:
                    continue
                n = len(e["clusters"])
                if rel in used:
                    skipped.append((rel, "already damaged by an earlier case"))
                    continue
                if e["resident"]:
                    skipped.append((rel, "resident in its MFT record"))
                    continue
                if n < step["min_clusters"]:
                    skipped.append((rel, "%d clusters, needs %d" % (n, step["min_clusters"])))
                    continue
                # Only the clusters about to be damaged need an unambiguous
                # location: damaging a duplicate would hit another file.
                if any(i in e["ambiguous"] for i in targets(step, n)):
                    skipped.append((rel, "target clusters duplicated elsewhere"))
                    continue
                # Still wholly intact after the filesystem-level overwrites, so
                # this damage is the only thing that happened to it. The last
                # cluster's hash covers only the file's bytes, not its slack.
                if not intact(mm, e, C):
                    lost = [i for i in range(n)
                            if overmap_h(mm, e, i, C) != e["hashes"][i]]
                    skipped.append((rel, "already lost clusters %s" % lost))
                    continue
                chosen = rel
                break
            if chosen is None:
                raise SystemExit(
                    "no intact deleted file for damage case %s; candidates:\n%s" % (
                        step["case"],
                        "\n".join("  %s: %s" % r for r in skipped) or "  (none of that kind)"))
            used.add(chosen)
            n = len(before["files"][chosen]["clusters"])
            idx = targets(step, n)
            for i in idx:
                o = before["files"][chosen]["clusters"][i]
                if step["fill"] == "random":
                    blob = bytes(rng.getrandbits(8) for _ in range(C))
                else:
                    blob = b"\xDB" * C
                mm[o:o + C] = blob
            done.append({"case": step["case"], "file": chosen, "clusters": idx,
                         "fill": step["fill"], "evidence": step["evidence"]})
        mm.flush()
        mm.close()
    json.dump({"seed": seed, "cases": done}, sys.stdout, indent=1)


# ------------------------------------------------------------------- truth


def classify(n, lost, header_lost):
    """The Milestone 5 policy, stated once.

    GREEN   nothing lost
    YELLOW  some clusters lost, but fewer than half and not the header
    RED     the header cluster lost, or half or more of the clusters

    A file with no clusters (resident in its MFT record) cannot lose any.
    """
    if n == 0 or lost == 0:
        return "GREEN"
    if header_lost or lost * 2 >= n:
        return "RED"
    return "YELLOW"


def cmd_truth(image, before_json, damage_json, live_json):
    before = json.load(open(before_json, encoding="utf-8"))
    damage = json.load(open(damage_json, encoding="utf-8"))
    live = set(json.load(open(live_json, encoding="utf-8"))["cluster_hashes"])
    C = before["cluster"]
    cases = {d["file"]: d for d in damage["cases"]}
    out, tally = {}, {}
    with open(image, "rb") as fh:
        mm = mmap.mmap(fh.fileno(), 0, access=mmap.ACCESS_READ)
        for rel, e in sorted(before["files"].items()):
            clusters = e["clusters"]
            overwritten, to_live, lost_idx = 0, 0, []
            for i, (o, want) in enumerate(zip(clusters, e.get("hashes", []))):
                now = mm[o:o + piece_len(e, i, C)]
                if h(now) == want:
                    continue
                lost_idx.append(i)
                if h(mm[o:o + C]) in live:
                    to_live += 1
                else:
                    overwritten += 1
            n = len(clusters)
            lost = len(lost_idx)
            header_lost = 0 in lost_idx
            cls = classify(n, lost, header_lost)
            how = []
            if rel in cases:
                how.append("targeted:" + cases[rel]["case"])
            if to_live:
                how.append("allocated-to-live-file")
            if overwritten and rel not in cases:
                how.append("filesystem-overwrite")
            out[rel] = {
                "clusters": n,
                "resident": e["resident"],
                "lost_clusters": lost,
                "lost_indices": lost_idx,
                "lost_to_live_file": to_live,
                "lost_overwritten": overwritten,
                "header_lost": header_lost,
                "class": cls,
                "damage": how or ["none"],
                "evidence_available": cases[rel]["evidence"] if rel in cases else None,
                # Clusters whose content also exists elsewhere, so their location
                # - and therefore whether *this* copy survived - is uncertain.
                "ambiguous_clusters": len(e["ambiguous"]),
            }
            tally[cls] = tally.get(cls, 0) + 1
        mm.close()
    json.dump({"policy": "GREEN nothing lost; RED header lost or >= half lost; else YELLOW",
               "counts": tally, "files": out}, sys.stdout, indent=1, sort_keys=True)


def main(argv):
    if len(argv) < 2:
        sys.stderr.write(__doc__)
        return 2
    cmd = argv[1]
    if cmd == "map" and len(argv) == 7:
        cmd_map(argv[2], argv[3], argv[4], argv[5], int(argv[6]))
    elif cmd == "livefile" and len(argv) == 6:
        cmd_livefile(argv[2], int(argv[3]), int(argv[4]), int(argv[5]))
    elif cmd == "damage" and len(argv) == 6:
        cmd_damage(argv[2], argv[3], int(argv[4]), argv[5])
    elif cmd == "truth" and len(argv) == 6:
        cmd_truth(argv[2], argv[3], argv[4], argv[5])
    else:
        sys.stderr.write(__doc__)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
